# Generated by Django 3.1.7 on 2021-02-27 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20210227_1459'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FeedbackAnswer',
        ),
    ]
